Adding new page for Security Settings to replace the Security Slider …
torproject/manual pull request #12
Opened 2019-03-25 18:15 UTC by andpersand

…page - the Security Slider directory will need to be removed. This update is to accompany the TB 8.5 release.

2019-03-25 18:16 UTC, andpersand commented
Creating a Security Settings page to accompany the TB 8.5 release. Alternatively, we can replace the contents.lr file in the security-slider folder with this contents.lr file.

2019-03-29 12:12 UTC, emmapeel2 requested changes
I have added it to staging for now, have a look at https://lektor-staging.torproject.org/tor-browser-manual/staging/en-US/security-settings/

Please see how I added the topic to the sidebar with 7bd6d39a82d1adb738ea84bf2b4b4da1d9b4540e 

I love the perfectly trimmed lines, thanks for taking l10n into account!

2019-03-29 12:12 UTC, emmapeel2 commented on content/security-settings/contents.lr
> +<img class="col-md-6" src="../../static/images/slider.png">
This screenshot should be replaced before going live

2019-03-29 12:12 UTC, emmapeel2 commented on content/security-settings/contents.lr
> +Increasing Tor Browser's security level will stop some web pages from functioning properly, so you should weigh your security needs against the degree of usability you require.
Maybe we can link here to some of the documents we have to help people assess their threat model?

2019-05-21 12:45 UTC, merged